resource_types:

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: pcf-gcp-concourse
  type: git
  source:
    uri: git@github.com:pivotal-customer0/pcf-gcp-concourse.git
    branch: mglynn-dev
    private_key: {{githubsshkey}}

- name: gcp-run-id
  type: semver
  source:
    bucket: concourse-gcp
    key: {{semver_file_name}}
    initial_version: 1.0.0
    access_key_id: {{aws_id}}
    secret_access_key: {{aws_key}}

jobs:
- name: WipeEnv-0
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp-concourse
      trigger: false
    - get: gcp-run-id
      params: {bump: major}
  - task: wipe-env
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/wipe-env.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        arg_wipe: {{arg_wipe}}
  - put: gcp-run-id
    params: {file: gcp-run-id/number}

- name: Terraform-IaaS-1
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp-concourse
      trigger: false
    - get: gcp-run-id
      trigger: true
      passed: [WipeEnv-0]
  - task: terrafrom-iaas
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/terraform-iaas.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        gcp_terraform_subnet_bosh: {{gcp_terraform_subnet_bosh}}
        gcp_terraform_subnet_concourse: {{gcp_terraform_subnet_concourse}}
        gcp_terraform_subnet_pcf_zone1: {{gcp_terraform_subnet_pcf_zone1}}
        gcp_terraform_subnet_pcf_zone2: {{gcp_terraform_subnet_pcf_zone2}}

- name: Deploy-Bosh-2
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp-concourse
      trigger: false
    - get: gcp-run-id
      trigger: true
      passed: [Terraform-IaaS-1]
  - task: deploy-bosh
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/deploy-bosh.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        gcp_terraform_subnet_bosh: {{gcp_terraform_subnet_bosh}}
        gcp_terraform_subnet_bosh_static: {{gcp_terraform_subnet_bosh_static}}
        gcp_terraform_subnet_bosh_gateway: {{gcp_terraform_subnet_bosh_gateway}}
        gcp_terraform_subnet_concourse: {{gcp_terraform_subnet_concourse}}
        gcp_terraform_subnet_concourse_gateway: {{gcp_terraform_subnet_concourse_gateway}}
        gcp_terraform_subnet_pcf_zone1: {{gcp_terraform_subnet_pcf_zone1}}
        gcp_terraform_subnet_pcf_zone1_gateway: {{gcp_terraform_subnet_pcf_zone1_gateway}}
        gcp_terraform_subnet_pcf_zone2: {{gcp_terraform_subnet_pcf_zone2}}
        gcp_terraform_subnet_pcf_zone2_gateway: {{gcp_terraform_subnet_pcf_zone2_gateway}}
        bosh_manifest_template: {{bosh_manifest_template}}
        bosh_cloud_config_template: {{bosh_cloud_config_template}}
        bosh_director_user: {{bosh_director_user}}
        bosh_director_password: {{bosh_director_password}}
        bosh_subnet_static:
        - {{bosh_subnet_static_range_1}}
        - {{bosh_subnet_static_range_2}}
        bosh_subnet_reserved:
        - {{bosh_subnet_reserved_range_1}}
        - {{bosh_subnet_reserved_range_2}}
        bosh_subnet_DNS:
        - {{bosh_subnet_DNS_range_1}}
        - {{bosh_subnet_DNS_range_2}}
        concourse_subnet_static:
        - {{concourse_subnet_static_range_1}}
        - {{concourse_subnet_static_range_2}}
        - {{concourse_subnet_static_range_3}}
        - {{concourse_subnet_static_range_4}}
        concourse_subnet_reserved:
        - {{concourse_subnet_reserved_range_1}}
        - {{concourse_subnet_reserved_range_2}}
        concourse_subnet_DNS:
        - {{concourse_subnet_DNS_range_1}}
        - {{concourse_subnet_DNS_range_2}}
        pcf_subnet_zone1_static:
        - {{pcf_subnet_zone1_static_range_1}}
        pcf_subnet_zone1_reserved:
        - {{pcf_subnet_zone1_reserved_range_1}}
        - {{pcf_subnet_zone1_reserved_range_2}}
        pcf_subnet_zone1_DNS:
        - {{pcf_subnet_zone1_DNS_range_1}}
        - {{pcf_subnet_zone1_DNS_range_2}}
        pcf_subnet_zone2_static:
        - {{pcf_subnet_zone2_static_range_1}}
        pcf_subnet_zone2_reserved:
        - {{pcf_subnet_zone2_reserved_range_1}}
        - {{pcf_subnet_zone2_reserved_range_2}}
        pcf_subnet_zone2_DNS:
        - {{pcf_subnet_zone2_DNS_range_1}}
        - {{pcf_subnet_zone2_DNS_range_2}}
        stemcell_version: {{stemcell_version}}

- name: Deploy-Concourse-3
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp-concourse
      trigger: false
    - get: gcp-run-id
      trigger: true
      passed: [Deploy-Bosh-2]
  - task: deploy-concourse
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/deploy-concourse.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        gcp_terraform_subnet_bosh: {{gcp_terraform_subnet_bosh}}
        gcp_terraform_subnet_bosh_static: {{gcp_terraform_subnet_bosh_static}}
        gcp_terraform_subnet_bosh_gateway: {{gcp_terraform_subnet_bosh_gateway}}
        gcp_terraform_subnet_concourse: {{gcp_terraform_subnet_concourse}}
        gcp_terraform_subnet_concourse_gateway: {{gcp_terraform_subnet_concourse_gateway}}
        bosh_director_user: {{bosh_director_user}}
        bosh_director_password: {{bosh_director_password}}
        concourse_manifest_template: {{concourse_manifest_template}}
        concourse_static_ips_web:
        -  {{concourse_subnet_static_range_1}}
        concourse_static_ips_db:
        -  {{concourse_subnet_static_range_2}}
        concourse_external_url: {{concourse_external_url}}
        concourse_basic_auth_username: {{concourse_basic_auth_username}}
        concourse_basic_auth_password: {{concourse_basic_auth_password}}
