resources:

- name: pcf-gcp
  type: git
  source:
    uri: git@github.com:pivotal-customer0/pcf-gcp.git
    branch: master
    private_key: {{githubsshkey}}

- name: pcf-gcp-concourse
  type: git
  source:
    uri: git@github.com:pivotal-customer0/pcf-gcp-concourse.git
    branch: master
    private_key: {{githubsshkey}}

#- name: bosh-gcp-cpi-release
#  type: git
#  source:
#    uri: ?
#    branch: master
#    private_key: {{githubsshkey}}


- name: gcp-run-id
  type: semver
  source:
    bucket: concourse-gcp
    key: {{semver_file_name}}
    initial_version: 1.0.0
    access_key_id: {{aws_id}}
    secret_access_key: {{aws_key}}

jobs:
- name: WipeEnv-0
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp-concourse
      trigger: false
  - task: wipe-env
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/wipe-env.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        arg_wipe: {{arg_wipe}}

- name: Terraform-IaaS-1
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-gcp
      trigger: false
    - get: pcf-gcp-concourse
      trigger: false
  - task: terrafrom-iaas
    config:
      platform: linux
      image: docker:///virtmerlin/pcf-gcp-worker
      inputs:
        - name: pcf-gcp
        - name: pcf-gcp-concourse
      run:
        path: pcf-gcp-concourse/tasks/terraform-iaas.sh
      params:
        gcp_proj_id: {{gcp_proj_id}}
        gcp_region: {{gcp_region}}
        gcp_zone_1: {{gcp_zone_1}}
        gcp_zone_2: {{gcp_zone_2}}
        gcp_svc_acct_key: {{gcp_svc_acct_key}}
        gcp_terraform_prefix: {{gcp_terraform_prefix}}
        gcp_terraform_subnet_bosh: {{gcp_terraform_subnet_bosh}}
        gcp_terraform_subnet_concourse_private: {{gcp_terraform_subnet_concourse_private}}
        gcp_terraform_subnet_concourse_public: {{gcp_terraform_subnet_concourse_public}}
        gcp_terraform_subnet_pcf_zone1_private: {{gcp_terraform_subnet_pcf_zone1_private}}
        gcp_terraform_subnet_pcf_zone1_public: {{gcp_terraform_subnet_pcf_zone1_public}}
        gcp_terraform_subnet_pcf_zone2_private: {{gcp_terraform_subnet_pcf_zone2_private}}
        gcp_terraform_subnet_pcf_zone2_public: {{gcp_terraform_subnet_pcf_zone2_public}}
